# -*- coding: utf-8 -*-
"""CommE5064_HW2_Q2_R13921031.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpQOqR73NDp4TFmHd3Ug76oPvpaDT6Zc
"""

# ============================================================================
# Cell 1: Title and Setup
# ============================================================================
"""
================================================================================
2024 Fall Artificial Intelligence and Intelligent Medicine
Homework 2 - Question 2: Dynamic Interaction Network and Relevance Value

Student Name: James Christian
Student ID: R13921031
Date: 2024-11-12

This notebook implements the solution to Q2, which involves:
(a) Understanding the matrix formulation of gene interaction networks
(b) Solving for interaction matrices A+ and A- using Ridge regression
(c) Calculating Relevance Values and identifying top-15 prognostic genes

Reference:
Cheng, L. H., Hsu, T. C., & Lin, C. (2021). Integrating ensemble systems
biology feature selection and bimodal deep neural network for breast cancer
prognosis prediction. Scientific Reports, 11(1), 1-10.
================================================================================
"""

# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Ridge
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

# ============================================================================
# Cell 2: Load and Inspect Data
# ============================================================================
"""
STEP 1: Load the data from AIIM_HW2_ANOVA_grouped_CADM1.npz

The dataset contains:
- x_pos: Gene expression data for positive group (separated by CADM1 marker)
- x_neg: Gene expression data for negative group
- ANOVA_genes: List of 329 genes selected by one-way ANOVA (p-value < 0.01)
"""

# Load the data (allow_pickle=True for gene names)
data = np.load('AIIM_HW2_ANOVA_grouped_CADM1.npz', allow_pickle=True)

# Check available keys
print("Available keys in the data file:")
print(list(data.keys()))
print()

# Load arrays
x_pos = data['x_pos']
x_neg = data['x_neg']
anova_genes = data['ANOVA_genes']

# Display basic information
print("Data loaded successfully!")
print(f"X+ (positive group) shape: {x_pos.shape}")
print(f"X- (negative group) shape: {x_neg.shape}")
print(f"Number of ANOVA-selected genes: {len(anova_genes)}")
print()

# Display first 10 gene names
print("First 10 gene names:")
print(anova_genes[:10])
print()

# Display basic statistics
print("X+ statistics:")
print(f"  Mean: {x_pos.mean():.4f}")
print(f"  Std: {x_pos.std():.4f}")
print(f"  Min: {x_pos.min():.4f}")
print(f"  Max: {x_pos.max():.4f}")
print()

print("X- statistics:")
print(f"  Mean: {x_neg.mean():.4f}")
print(f"  Std: {x_neg.std():.4f}")
print(f"  Min: {x_neg.min():.4f}")
print(f"  Max: {x_neg.max():.4f}")

# ============================================================================
# Cell 3: Data Preprocessing - Transpose Matrices
# ============================================================================
"""
STEP 2: Transpose matrices to get (genes × patients) format

Original data format: (patients × genes)
Required format: (genes × patients)

This is necessary because:
- Each row should represent one gene's expression across all patients
- Each column should represent one patient's expression across all genes
"""

# Verify current dimensions
print("Current matrix dimensions:")
print(f"X+ shape: {x_pos.shape}")
print(f"X- shape: {x_neg.shape}")
print(f"Number of gene names: {len(anova_genes)}")
print()

# Check orientation
if x_pos.shape[1] == len(anova_genes):
    print("✓ Confirmed: Columns = genes (329), Rows = patients")
    print(f"  X+ has {x_pos.shape[0]} patients in positive group")
    print(f"  X- has {x_neg.shape[0]} patients in negative group")
    print("\n⚠️  Need to transpose matrices!")
    print()

    # Transpose to get (genes × patients)
    X_pos = x_pos.T  # Now (329 genes × 27 patients)
    X_neg = x_neg.T  # Now (329 genes × 28 patients)

    print("After transposing:")
    print(f"X+ shape: {X_pos.shape} (genes × patients)")
    print(f"X- shape: {X_neg.shape} (genes × patients)")
    print()

    # Verify: first gene's expression across first 5 patients
    print(f"First gene '{anova_genes[0]}' expression in first 5 patients of X+:")
    print(X_pos[0, :5])
    print()

    print("✓ Data preprocessing complete!")
    print(f"Ready to create {len(anova_genes)} × {len(anova_genes)} interaction matrices")

# ============================================================================
# Cell 4: Q2(a) - Matrix Elements Explanation
# ============================================================================
"""
================================================================================
Q2(a): State the Elements in Each Matrix
================================================================================

Given equation:
    x_i[n] = Σ(j∈G, j≠i) a_ij * x_j[n] + ε_i[n]

where:
    x_i[n] = expression level of gene i for patient n
    a_ij = interaction ability between gene i and j
    G = selected pool of genes (ANOVA genes)
    ε_i[n] = stochastic noise

Matrix form: X(n) = A·X(n) + E(n)
"""

def explain_matrix_elements():
    """
    Provides a detailed explanation of each matrix in X(n) = A·X(n) + E(n)
    """

    print("=" * 80)
    print("Q2(a): MATRIX ELEMENTS IN X(n) = A·X(n) + E(n)")
    print("=" * 80)
    print()

    # Matrix X
    print("1. MATRIX X (Expression Matrix)")
    print("-" * 80)
    print("   Dimensions: M × N (genes × patients)")
    print(f"   - M = {len(anova_genes)} (number of ANOVA-selected genes)")
    print(f"   - N = number of patients in group (27 for X+, 28 for X-)")
    print()
    print("   Elements: X[i, n] = expression level of gene i for patient n")
    print()
    print("   Interpretation:")
    print("   - Each row represents one gene's expression across all patients")
    print("   - Each column represents one patient's expression across all genes")
    print("   - Contains measured gene expression values from microarray data")
    print()

    # Matrix A
    print("2. MATRIX A (Interaction Ability Matrix)")
    print("-" * 80)
    print("   Dimensions: M × M (genes × genes)")
    print(f"   - Shape: {len(anova_genes)} × {len(anova_genes)}")
    print()
    print("   Elements: A[i, j] = interaction ability from gene j to gene i")
    print()
    print("   ⚠️  SPECIAL PROPERTY - Diagonal Elements:")
    print("   " + "=" * 70)
    print("   A[i, i] = 0 for all i ∈ {1, 2, ..., M}")
    print("   " + "=" * 70)
    print()
    print("   Explanation:")
    print("   The diagonal of A must be zero because in the original summation")
    print("   Σ(j∈G, j≠i), we explicitly exclude j = i. This means gene i is NOT")
    print("   used to predict its own expression. Each gene's expression is modeled")
    print("   as a linear combination of OTHER genes' expressions only.")
    print()
    print("   Interpretation:")
    print("   - A[i, j] represents how strongly gene j influences gene i")
    print("   - Larger |A[i, j]| indicates stronger interaction")
    print("   - Positive A[i, j]: gene j upregulates gene i")
    print("   - Negative A[i, j]: gene j downregulates gene i")
    print()

    # Matrix E
    print("3. MATRIX E (Noise Matrix)")
    print("-" * 80)
    print("   Dimensions: M × N (genes × patients)")
    print(f"   - Shape: {len(anova_genes)} × N")
    print()
    print("   Elements: E[i, n] = stochastic noise for gene i in patient n")
    print()
    print("   Interpretation:")
    print("   - Captures unexplained variance in gene expression")
    print("   - Includes measurement noise and biological variability")
    print("   - Represents effects from genes not included in G")
    print("   - Models deviations from perfect linear interactions")
    print()

    print("=" * 80)
    print("SUMMARY: The model assumes each gene's expression is a linear")
    print("combination of other genes' expressions plus noise, forming a")
    print("gene regulatory network where interactions are quantified by matrix A.")
    print("=" * 80)
    print()

# Display the explanation
explain_matrix_elements()

# ============================================================================
# Cell 5: Q2(b) - Function to Solve Interaction Matrix
# ============================================================================
"""
================================================================================
Q2(b): Solve for Interaction Matrices A+ and A-
================================================================================

Method: Ridge Regression (Linear Regression with L2 Regularization)

For each gene i:
    1. Target (y): Expression of gene i across all patients
    2. Predictors (X): Expression of all OTHER genes (j ≠ i)
    3. Model: Ridge regression with regularization coefficient α = 1
    4. Solution: Coefficients become row i of matrix A
    5. Constraint: A[i, i] = 0 (diagonal element)

Mathematical formulation:
    minimize: ||y - X·β||² + α||β||²

    where α = 1 is the L2 regularization coefficient

Closed-form solution:
    β = (X^T·X + αI)^(-1)·X^T·y
"""

def solve_interaction_matrix(X, alpha=1.0, verbose=True):
    """
    Solve for the interaction ability matrix A using Ridge regression.

    For each gene i, we solve the optimization problem:
        minimize ||x_i - Σ(j≠i) a_ij·x_j||² + α·Σ(j≠i) a_ij²

    This is equivalent to Ridge regression where:
        - Target: x_i (expression of gene i)
        - Features: x_j for all j ≠ i (expression of other genes)
        - Regularization: L2 penalty with coefficient α

    Parameters:
    -----------
    X : numpy.ndarray
        Expression matrix of shape (M, N) where:
        - M = number of genes
        - N = number of patients
    alpha : float, default=1.0
        L2 regularization coefficient (as specified in homework)
    verbose : bool, default=True
        Whether to print progress information

    Returns:
    --------
    A : numpy.ndarray
        Interaction ability matrix of shape (M, M)
        - A[i, j] = interaction ability from gene j to gene i
        - Diagonal elements A[i, i] = 0 (as required)

    Notes:
    ------
    - Ridge regression is used to prevent overfitting given limited samples
    - L2 regularization handles multicollinearity among gene expressions
    - Diagonal constraint ensures gene i doesn't predict itself
    """

    M, N = X.shape  # M = genes, N = patients
    A = np.zeros((M, M))  # Initialize interaction matrix

    if verbose:
        print(f"Solving for interaction matrix A...")
        print(f"  Matrix dimensions: {M} genes × {N} patients")
        print(f"  L2 regularization coefficient (alpha): {alpha}")
        print(f"  Method: Ridge Regression (scikit-learn)")
        print()

    # For each gene i, fit a Ridge regression model
    for i in range(M):
        # Target: expression of gene i across all patients
        # Shape: (N,) - one value per patient
        y = X[i, :]

        # Predictors: expression of all OTHER genes (exclude gene i)
        # Create boolean mask to exclude gene i
        mask = np.ones(M, dtype=bool)
        mask[i] = False  # Set gene i to False

        # Extract predictor matrix (all genes except i)
        # X[mask, :] gives (M-1) × N, then transpose to get N × (M-1)
        # This gives us patients as rows, genes as columns (standard format)
        X_pred = X[mask, :].T  # Shape: (N, M-1)

        # Fit Ridge regression with L2 regularization
        # fit_intercept=False because we assume the data is already centered
        # and we want a pure linear combination without bias term
        ridge = Ridge(alpha=alpha, fit_intercept=False)
        ridge.fit(X_pred, y)

        # Extract coefficients (interaction abilities)
        # ridge.coef_ has shape (M-1,) containing a_ij for all j ≠ i
        coef = ridge.coef_

        # Place coefficients in row i of matrix A
        # mask selects all positions except diagonal (where j ≠ i)
        A[i, mask] = coef

        # A[i, i] remains 0 (already initialized to 0)
        # This satisfies the constraint that gene i doesn't predict itself

        # Print progress every 50 genes
        if verbose and (i + 1) % 50 == 0:
            print(f"    Processed {i + 1}/{M} genes...")

    # Verify the diagonal constraint
    diagonal_sum = np.sum(np.diag(A))

    if verbose:
        print(f"  ✓ Completed!")
        print(f"  Verification: Diagonal sum = {diagonal_sum:.10f} (should be 0.0)")
        print()

    return A

# ============================================================================
# Cell 6: Solve for A+ (Positive Group)
# ============================================================================
"""
Solve the interaction matrix A+ for the positive group (X+)

Input:
    - X_pos: (329 genes × 27 patients) expression matrix
    - alpha: L2 regularization coefficient = 1.0

Output:
    - A_pos: (329 × 329) interaction ability matrix
    - Diagonal elements = 0
"""

print("=" * 80)
print("SOLVING FOR A+ (POSITIVE GROUP)")
print("=" * 80)
print()

# Solve for A+ using Ridge regression with alpha=1
A_pos = solve_interaction_matrix(X_pos, alpha=1.0, verbose=True)

# Display results
print("=" * 80)
print("A+ RESULTS")
print("=" * 80)
print(f"Shape: {A_pos.shape}")
print()
print("Statistics:")
print(f"  Mean: {A_pos.mean():.6f}")
print(f"  Std:  {A_pos.std():.6f}")
print(f"  Min:  {A_pos.min():.6f}")
print(f"  Max:  {A_pos.max():.6f}")
print()
print(f"Non-zero elements: {np.count_nonzero(A_pos):,} / {A_pos.size:,} ({100*np.count_nonzero(A_pos)/A_pos.size:.2f}%)")
print()

# Verify diagonal is exactly zero
print("Verification:")
print(f"  Diagonal elements (first 10): {np.diag(A_pos)[:10]}")
print(f"  Sum of all diagonal elements: {np.sum(np.diag(A_pos)):.15f}")
print(f"  ✓ Diagonal constraint satisfied: A[i,i] = 0 for all i")
print("=" * 80)

# ============================================================================
# Cell 7: Solve for A- (Negative Group)
# ============================================================================
"""
Solve the interaction matrix A- for the negative group (X-)

Input:
    - X_neg: (329 genes × 28 patients) expression matrix
    - alpha: L2 regularization coefficient = 1.0

Output:
    - A_neg: (329 × 329) interaction ability matrix
    - Diagonal elements = 0
"""

print()
print("=" * 80)
print("SOLVING FOR A- (NEGATIVE GROUP)")
print("=" * 80)
print()

# Solve for A- using Ridge regression with alpha=1
A_neg = solve_interaction_matrix(X_neg, alpha=1.0, verbose=True)

# Display results
print("=" * 80)
print("A- RESULTS")
print("=" * 80)
print(f"Shape: {A_neg.shape}")
print()
print("Statistics:")
print(f"  Mean: {A_neg.mean():.6f}")
print(f"  Std:  {A_neg.std():.6f}")
print(f"  Min:  {A_neg.min():.6f}")
print(f"  Max:  {A_neg.max():.6f}")
print()
print(f"Non-zero elements: {np.count_nonzero(A_neg):,} / {A_neg.size:,} ({100*np.count_nonzero(A_neg)/A_neg.size:.2f}%)")
print()

# Verify diagonal is exactly zero
print("Verification:")
print(f"  Diagonal elements (first 10): {np.diag(A_neg)[:10]}")
print(f"  Sum of all diagonal elements: {np.sum(np.diag(A_neg)):.15f}")
print(f"  ✓ Diagonal constraint satisfied: A[i,i] = 0 for all i")
print("=" * 80)

print()
print("=" * 80)
print("✓ BOTH A+ AND A- SOLVED SUCCESSFULLY!")
print("=" * 80)

# ============================================================================
# Cell 8: Q2(c) - Calculate Relevance Values
# ============================================================================
"""
================================================================================
Q2(c): Calculate Relevance Values (RVs) and Identify Top-15 Genes
================================================================================

Definition of Relevance Value:
    RV_i = Σ_j |D[i, j]|

where:
    D = A+ - A-  (difference matrix)

Interpretation:
    - D[i, j] = change in interaction ability from gene j to gene i
    - RV_i sums absolute changes across all interaction partners
    - Higher RV_i indicates more differential interactions between groups
    - Genes with high RVs are potential prognostic biomarkers
"""

def calculate_relevance_values(A_pos, A_neg, gene_names, verbose=True):
    """
    Calculate Relevance Values (RVs) for all genes.

    The RV measures how differently a gene interacts with other genes
    between the positive and negative prognosis groups.

    Parameters:
    -----------
    A_pos : numpy.ndarray
        Interaction matrix for positive group (M × M)
    A_neg : numpy.ndarray
        Interaction matrix for negative group (M × M)
    gene_names : list or numpy.ndarray
        Names of the genes (length M)
    verbose : bool, default=True
        Whether to print detailed information

    Returns:
    --------
    rv_df : pandas.DataFrame
        DataFrame with columns ['Gene', 'RV'] sorted by RV (descending)
        Contains all genes ranked by their relevance values

    Notes:
    ------
    The RV is calculated as:
        RV_i = Σ(j=1 to M) |D[i,j]|
    where D = A+ - A- is the difference matrix.

    High RV indicates the gene has significantly different interaction
    patterns between the two prognosis groups, making it a potential
    prognostic biomarker.
    """

    if verbose:
        print("=" * 80)
        print("CALCULATING RELEVANCE VALUES")
        print("=" * 80)
        print()

    # Step 1: Calculate difference matrix D = A+ - A-
    # This shows how interactions change between positive and negative groups
    D = A_pos - A_neg

    if verbose:
        print("Step 1: Calculate Difference Matrix D = A+ - A-")
        print(f"  D shape: {D.shape}")
        print(f"  D statistics:")
        print(f"    Mean: {D.mean():.6f} (should be close to 0)")
        print(f"    Std:  {D.std():.6f}")
        print(f"    Min:  {D.min():.6f}")
        print(f"    Max:  {D.max():.6f}")
        print()

    # Step 2: Calculate RV for each gene
    # RV_i = sum of absolute values in row i of D
    # This represents the total change in interactions for gene i
    RV = np.sum(np.abs(D), axis=1)

    if verbose:
        print("Step 2: Calculate RV for each gene")
        print(f"  Formula: RV_i = Σ_j |D[i, j]|")
        print(f"  Number of genes: {len(RV)}")
        print()
        print(f"  RV statistics:")
        print(f"    Mean: {RV.mean():.6f}")
        print(f"    Std:  {RV.std():.6f}")
        print(f"    Min:  {RV.min():.6f}")
        print(f"    Max:  {RV.max():.6f}")
        print()

    # Step 3: Create DataFrame and sort by RV
    rv_df = pd.DataFrame({
        'Gene': gene_names,
        'RV': RV
    })

    # Sort by RV in descending order (highest RV first)
    rv_df = rv_df.sort_values('RV', ascending=False).reset_index(drop=True)

    if verbose:
        print("Step 3: Rank genes by RV")
        print(f"  ✓ All {len(rv_df)} genes ranked successfully")
        print()
        print("=" * 80)
        print()

    return rv_df, D


# Calculate RVs
rv_df, D = calculate_relevance_values(A_pos, A_neg, anova_genes, verbose=True)

# ============================================================================
# Cell 9: Extract and Display Top-15 Genes
# ============================================================================
"""
Extract the top 15 genes with highest Relevance Values

These genes show the most differential interaction patterns between
the positive and negative prognosis groups, making them strong candidates
for prognostic biomarkers.
"""

def get_top_genes(rv_df, n=15):
    """
    Extract top N genes with highest Relevance Values.

    Parameters:
    -----------
    rv_df : pandas.DataFrame
        DataFrame with columns ['Gene', 'RV'] sorted by RV
    n : int, default=15
        Number of top genes to extract

    Returns:
    --------
    top_genes : pandas.DataFrame
        DataFrame with columns ['Rank', 'Gene', 'RV'] for top N genes
    """

    top_genes = rv_df.head(n).copy()
    top_genes.insert(0, 'Rank', range(1, n + 1))

    return top_genes


# Extract top 15 genes
top_15 = get_top_genes(rv_df, n=15)

# Display results
print("=" * 80)
print("TOP 15 GENES WITH HIGHEST RELEVANCE VALUES")
print("=" * 80)
print()
print(top_15.to_string(index=False))
print()
print("=" * 80)
print()

# Highlight the top gene
print(f"🏆 Highest RV Gene: {top_15.iloc[0]['Gene']} (RV = {top_15.iloc[0]['RV']:.6f})")
print(f"   This gene shows the strongest differential interaction pattern")
print(f"   between positive and negative prognosis groups.")
print()

# Summary statistics for top 15
print("Top 15 Summary:")
print(f"  RV range: {top_15['RV'].min():.6f} to {top_15['RV'].max():.6f}")
print(f"  Mean RV (top 15): {top_15['RV'].mean():.6f}")
print(f"  Mean RV (all genes): {rv_df['RV'].mean():.6f}")
print(f"  Top 15 are {top_15['RV'].mean() / rv_df['RV'].mean():.2f}x above average")
print()
print("=" * 80)

# ============================================================================
# Cell 10: Save Results to Files
# ============================================================================
"""
Save all computed results to files for submission and further analysis
"""

import os

# Create output directory if it doesn't exist
os.makedirs('results', exist_ok=True)

print("=" * 80)
print("SAVING RESULTS TO FILES")
print("=" * 80)
print()

# Save interaction matrices as .npy files (binary, compact)
np.save('results/A_positive.npy', A_pos)
print("✓ Saved: results/A_positive.npy")

np.save('results/A_negative.npy', A_neg)
print("✓ Saved: results/A_negative.npy")

# Save difference matrix
np.save('results/D_difference.npy', D)
print("✓ Saved: results/D_difference.npy")

# Save all RV results as CSV
rv_df.to_csv('results/relevance_values_all_genes.csv', index=False)
print("✓ Saved: results/relevance_values_all_genes.csv")

# Save top 15 genes as CSV
top_15.to_csv('results/top_15_genes_by_RV.csv', index=False)
print("✓ Saved: results/top_15_genes_by_RV.csv")

print()
print("=" * 80)
print("All results saved successfully in 'results/' directory!")
print("=" * 80)

# ============================================================================
# Cell 11: Visualization - RV Distribution
# ============================================================================
"""
Create visualizations to understand the Relevance Value distribution
and the characteristics of top genes
"""

# Set plotting style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Create figures directory
os.makedirs('figures', exist_ok=True)

print("\nGenerating visualizations...")

# Figure 1: RV Distribution
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram
axes[0].hist(rv_df['RV'], bins=50, color='steelblue', edgecolor='black', alpha=0.7)
axes[0].axvline(rv_df['RV'].mean(), color='red', linestyle='--', linewidth=2,
                label=f'Mean = {rv_df["RV"].mean():.2f}')
axes[0].axvline(rv_df['RV'].median(), color='green', linestyle='--', linewidth=2,
                label=f'Median = {rv_df["RV"].median():.2f}')
axes[0].set_xlabel('Relevance Value (RV)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Frequency', fontsize=12, fontweight='bold')
axes[0].set_title('Distribution of Relevance Values (All 329 Genes)',
                  fontsize=13, fontweight='bold')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Box plot
axes[1].boxplot(rv_df['RV'], vert=True, patch_artist=True,
                boxprops=dict(facecolor='lightblue', alpha=0.7),
                medianprops=dict(color='red', linewidth=2),
                whiskerprops=dict(linewidth=1.5),
                capprops=dict(linewidth=1.5))
axes[1].set_ylabel('Relevance Value (RV)', fontsize=12, fontweight='bold')
axes[1].set_title('RV Distribution (Box Plot)', fontsize=13, fontweight='bold')
axes[1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('figures/fig1_rv_distribution.png', dpi=300, bbox_inches='tight')
print("✓ Saved: figures/fig1_rv_distribution.png")
plt.show()

# ============================================================================
# Cell 12: Visualization - Top 15 Genes Bar Chart
# ============================================================================
"""
Visualize the top 15 genes with highest Relevance Values
"""

fig, ax = plt.subplots(figsize=(10, 8))

# Create color gradient for bars
colors = plt.cm.viridis(np.linspace(0.3, 0.9, 15))

# Create horizontal bar chart (reversed to show rank 1 at top)
bars = ax.barh(range(15), top_15['RV'].values[::-1],
               color=colors[::-1], edgecolor='black', linewidth=1.2)

# Set gene names as y-tick labels
ax.set_yticks(range(15))
ax.set_yticklabels(top_15['Gene'].values[::-1], fontsize=11, fontweight='bold')
ax.set_xlabel('Relevance Value (RV)', fontsize=12, fontweight='bold')
ax.set_title('Top 15 Genes with Highest Relevance Values',
             fontsize=14, fontweight='bold', pad=20)
ax.grid(True, alpha=0.3, axis='x')

# Add value labels on bars
for i, (bar, val) in enumerate(zip(bars, top_15['RV'].values[::-1])):
    ax.text(val + 0.1, bar.get_y() + bar.get_height()/2, f'{val:.2f}',
            va='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('figures/fig2_top15_genes.png', dpi=300, bbox_inches='tight')
print("✓ Saved: figures/fig2_top15_genes.png")
plt.show()

# ============================================================================
# Cell 13: Visualization - Interaction Heatmaps
# ============================================================================
"""
Visualize interaction matrices for the top 15 genes
Shows A+, A-, and their difference D
"""

# Get indices of top 15 genes
top_15_indices = [np.where(anova_genes == gene)[0][0] for gene in top_15['Gene']]

# Extract submatrices for top 15 genes
A_pos_top15 = A_pos[np.ix_(top_15_indices, top_15_indices)]
A_neg_top15 = A_neg[np.ix_(top_15_indices, top_15_indices)]
D_top15 = D[np.ix_(top_15_indices, top_15_indices)]

# Create figure with 3 subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# A+ heatmap
sns.heatmap(A_pos_top15, cmap='RdBu_r', center=0,
            xticklabels=top_15['Gene'], yticklabels=top_15['Gene'],
            cbar_kws={'label': 'Interaction Strength'}, ax=axes[0],
            square=True, linewidths=0.5, linecolor='gray')
axes[0].set_title('A+ (Positive Group)\nTop 15 Genes', fontsize=12, fontweight='bold')
axes[0].tick_params(axis='both', labelsize=8)

# A- heatmap
sns.heatmap(A_neg_top15, cmap='RdBu_r', center=0,
            xticklabels=top_15['Gene'], yticklabels=top_15['Gene'],
            cbar_kws={'label': 'Interaction Strength'}, ax=axes[1],
            square=True, linewidths=0.5, linecolor='gray')
axes[1].set_title('A- (Negative Group)\nTop 15 Genes', fontsize=12, fontweight='bold')
axes[1].tick_params(axis='both', labelsize=8)

# Difference D heatmap
sns.heatmap(D_top15, cmap='RdBu_r', center=0,
            xticklabels=top_15['Gene'], yticklabels=top_15['Gene'],
            cbar_kws={'label': 'Difference (A+ - A-)'}, ax=axes[2],
            square=True, linewidths=0.5, linecolor='gray')
axes[2].set_title('D = A+ - A-\nTop 15 Genes', fontsize=12, fontweight='bold')
axes[2].tick_params(axis='both', labelsize=8)

plt.tight_layout()
plt.savefig('figures/fig3_interaction_heatmaps.png', dpi=300, bbox_inches='tight')
print("✓ Saved: figures/fig3_interaction_heatmaps.png")
plt.show()

# ============================================================================
# Cell 14: Visualization - Cumulative RV Plot
# ============================================================================
"""
Show how cumulative RV increases with the number of top genes selected
Helps understand how many genes are needed to capture most of the signal
"""

fig, ax = plt.subplots(figsize=(10, 6))

# Calculate cumulative RV
cumulative_rv = np.cumsum(rv_df['RV'].values)
cumulative_pct = 100 * cumulative_rv / cumulative_rv[-1]

# Plot cumulative percentage
ax.plot(range(1, len(rv_df) + 1), cumulative_pct, linewidth=2.5, color='darkblue')

# Add reference lines
ax.axhline(50, color='red', linestyle='--', linewidth=2, label='50% of total RV')
ax.axhline(80, color='orange', linestyle='--', linewidth=2, label='80% of total RV')

# Mark top 15
ax.axvline(15, color='green', linestyle='--', linewidth=2, label='Top 15 genes')
ax.fill_between(range(1, 16), 0, 100, alpha=0.2, color='green')

ax.set_xlabel('Number of Top Genes (Ranked by RV)', fontsize=12, fontweight='bold')
ax.set_ylabel('Cumulative % of Total RV', fontsize=12, fontweight='bold')
ax.set_title('Cumulative Relevance Value Distribution', fontsize=14, fontweight='bold')
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 100)

plt.tight_layout()
plt.savefig('figures/fig4_cumulative_rv.png', dpi=300, bbox_inches='tight')
print("✓ Saved: figures/fig4_cumulative_rv.png")
plt.show()

# ============================================================================
# Cell 15: Final Summary and Conclusion
# ============================================================================
"""
================================================================================
HOMEWORK Q2 COMPLETE SUMMARY
================================================================================
"""

print("\n" + "=" * 80)
print("HOMEWORK Q2 COMPLETE SUMMARY")
print("=" * 80)
print()

print("Q2(a) - Matrix Elements ✓")
print("-" * 80)
print("  X: (329 genes × N patients) - Expression matrix")
print("  A: (329 × 329) - Interaction matrix")
print("     ⚠️  Special property: A[i,i] = 0 (diagonal is zero)")
print("  E: (329 × N) - Noise matrix")
print()

print("Q2(b) - Solved Interaction Matrices ✓")
print("-" * 80)
print(f"  A+ (positive group): 329 × 329 matrix from {X_pos.shape[1]} patients")
print(f"  A- (negative group): 329 × 329 matrix from {X_neg.shape[1]} patients")
print("  Method: Ridge Regression with alpha=1.0")
print(f"  Both matrices have diagonal sum = 0.0")
print()

print("Q2(c) - Top 15 Genes by Relevance Value ✓")
print("-" * 80)
for idx, row in top_15.iterrows():
    print(f"  {row['Rank']:2d}. {row['Gene']:15s} RV = {row['RV']:.6f}")
print()

print("Files Generated:")
print("-" * 80)
print("Results:")
print("  - results/A_positive.npy")
print("  - results/A_negative.npy")
print("  - results/D_difference.npy")
print("  - results/relevance_values_all_genes.csv")
print("  - results/top_15_genes_by_RV.csv")
print()
print("Figures:")
print("  - figures/fig1_rv_distribution.png")
print("  - figures/fig2_top15_genes.png")
print("  - figures/fig3_interaction_heatmaps.png")
print("  - figures/fig4_cumulative_rv.png")
print()

print("=" * 80)
print("✅ HOMEWORK Q2 COMPLETED SUCCESSFULLY!")
print("=" * 80)
print()
print("Key Findings:")
print(f"  • {top_15.iloc[0]['Gene']} has the highest RV ({top_15.iloc[0]['RV']:.2f})")
print(f"  • Top 15 genes show strong differential interactions")
print(f"  • All diagonal constraints verified: A[i,i] = 0")
print(f"  • Ready for submission!")
print()
print("=" * 80)

# -*- coding: utf-8 -*-
"""CommE5064_HW2_Q3_R13921031.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGW5qiT4Ta_UYblWFMRJE1hWOV7Af1Gt

2024 Fall Artificial Intelligence and Intelligent Medicine
Homework 2 - Question 3: Biological Enrichment

Student Name: James Christian
Student ID: R13921031
Date: 2024-11-12

This notebook implements the solution to Q3, which involves:
 - (a) STRING network analysis with top-15 RV genes and biomarkers
 - (b) Identification of three cancer-related functions
 - (c) BioGRID analysis with CADM1 interacting genes and repeat of (a) and (b)

Tools used:
- STRING (https://string-db.org/) - Protein-protein interaction database
- BioGRID (https://thebiogrid.org/) - Biological interaction database

# Q3: Biological Enrichment Analysis

## Overview

This notebook performs biological enrichment analysis to identify cancer-related functions of genes identified through:
1. Relevance Value analysis (Q2) combined with known biomarkers
2. CADM1 interaction network from BioGRID

We use STRING database for protein-protein interaction network analysis and functional enrichment.
"""

# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

"""---
# Q3(a): STRING Network Analysis with Top-15 RV Genes + Biomarkers
---

## Step 1: Prepare Gene List for STRING

We combine two sets of genes:
1. **Top 15 genes with highest Relevance Values** (from Q2)
2. **Well-known cancer biomarkers** as specified in the homework
"""

# Top 15 genes from Q2(c) - Replace with your actual top 15 genes
# These are example genes - you should load your actual results from Q2
top_15_genes = [
    'PLAC8', 'MMP9', 'FAM198B', 'PRICKLE1', 'ZFP3',
    'ZNF383', 'LOC202181', 'SNORD89', 'LOC389765', 'S100A16',
    'NDUFAF2', 'HOXB2', 'ADAMTS5', 'SCIN', 'ANKRD12'
]

# Well-known biomarkers provided in the homework
biomarkers = ['EPCAM', 'HIF1A', 'PKM', 'PTK7', 'ALCAM', 'CADM1', 'SLC2A1']

# Combine both lists
all_genes_for_string = top_15_genes + biomarkers

print("=" * 80)
print("Q3(a): Preparing Gene List for STRING Analysis")
print("=" * 80)
print()

print(f"Top 15 RV Genes ({len(top_15_genes)}):")
for i, gene in enumerate(top_15_genes, 1):
    print(f"  {i:2d}. {gene}")
print()

print(f"Well-known Biomarkers ({len(biomarkers)}):")
for i, gene in enumerate(biomarkers, 1):
    print(f"  {i:2d}. {gene}")
print()

print(f"Total genes for STRING: {len(all_genes_for_string)}")
print()

# Create the input string for STRING (one gene per line)
string_input = '\n'.join(all_genes_for_string)

print("=" * 80)
print("STRING Input (copy this):")
print("=" * 80)
print(string_input)
print("=" * 80)
print()

# Save to file for easy copying
with open('string_input_genes.txt', 'w') as f:
    f.write(string_input)

print("✓ Gene list saved to: string_input_genes.txt")

"""## Step 2: Manual STRING Analysis

**Action Required:**

1. Go to https://string-db.org/
2. Paste the gene list (from above or from the file)
3. Select organism: **Homo sapiens**
4. Click **SEARCH**
5. Take a screenshot of the network visualization
6. Save as: `string_network_top15_biomarkers.png`
7. Go to the **Analysis** tab
8. Download **"All enriched terms (without PubMed)"** as TSV file
9. Upload the TSV file and continue below

---
# Q3(b): Identify Three Cancer-Related Functions
---

## Step 3: Load and Analyze STRING Enrichment Data
"""

# Load the enrichment file from STRING
# Replace 'enrichment_all.tsv' with your actual filename
enrichment_df = pd.read_csv('enrichment.all.tsv', sep='\t')

print("=" * 80)
print("STRING Enrichment Data - Analysis")
print("=" * 80)
print()

# Display basic info
print(f"Total enrichment terms: {len(enrichment_df)}")
print()

# Count by category
print("Enrichment by Category:")
print(enrichment_df['#category'].value_counts())
print()

# Show available categories
print("Available Categories:")
for cat in enrichment_df['#category'].unique():
    count = len(enrichment_df[enrichment_df['#category'] == cat])
    print(f"  - {cat}: {count} terms")
print()

"""## Step 4: Filter for Cancer-Related Terms"""

# Filter for cancer-related keywords
cancer_keywords = ['cancer', 'tumor', 'carcinoma', 'oncogene', 'metastasis',
                   'proliferation', 'apoptosis', 'angiogenesis', 'glycolysis',
                   'hypoxia', 'metabolism']

print("=" * 80)
print("CANCER-RELATED ENRICHMENT TERMS")
print("=" * 80)
print()

# Look for cancer-related terms in each category
for category in enrichment_df['#category'].unique():
    cat_df = enrichment_df[enrichment_df['#category'] == category]

    # Filter for cancer-related terms
    cancer_terms = cat_df[
        cat_df['term description'].str.lower().str.contains('|'.join(cancer_keywords), na=False)
    ].head(10)

    if len(cancer_terms) > 0:
        print(f"\n{category.upper()}:")
        print("-" * 80)
        for idx, row in cancer_terms.iterrows():
            print(f"  {row['term ID']}: {row['term description']}")
            print(f"    Genes: {row['observed gene count']}, FDR: {row['false discovery rate']:.4f}")
            print(f"    Proteins: {row['matching proteins in your network (labels)']}")
            print()

"""## Step 5: Select Three Most Significant Cancer-Related Functions"""

print("=" * 80)
print("Q3(b): THREE SELECTED CANCER-RELATED FUNCTIONS")
print("=" * 80)
print()

# Based on the enrichment data, select the top 3 most significant cancer-related functions
# These should be adjusted based on your actual enrichment results

print("FUNCTION 1: Central Carbon Metabolism in Cancer")
print("  Category: KEGG Pathway")
print("  Term ID: hsa05230")
print("  Genes: PKM, SLC2A1, HIF1A")
print("  FDR: 0.0140")
print("  Strength: 1.66")
print()

print("FUNCTION 2: Glucose Metabolism in Triple-Negative Breast Cancer Cells")
print("  Category: WikiPathways")
print("  Term ID: WP5211")
print("  Genes: PKM, SLC2A1")
print("  FDR: 0.0083")
print("  Strength: 2.41")
print()

print("FUNCTION 3: HIF1A and PPARG Regulation of Glycolysis")
print("  Category: WikiPathways")
print("  Term ID: WP2456")
print("  Genes: SLC2A1, HIF1A")
print("  FDR: 0.0083")
print("  Strength: 2.41")
print()

print("=" * 80)

# Save the selected functions
selected_functions_q3b = pd.DataFrame({
    'Function': [
        'Central Carbon Metabolism in Cancer',
        'Glucose Metabolism in Triple-Negative Breast Cancer Cells',
        'HIF1A and PPARG Regulation of Glycolysis'
    ],
    'Category': ['KEGG Pathway', 'WikiPathways', 'WikiPathways'],
    'Term ID': ['hsa05230', 'WP5211', 'WP2456'],
    'Genes': ['PKM, SLC2A1, HIF1A', 'PKM, SLC2A1', 'SLC2A1, HIF1A'],
    'FDR': [0.0140, 0.0083, 0.0083]
})

selected_functions_q3b.to_csv('q3b_selected_functions.csv', index=False)
print("\n✓ Selected functions saved to: q3b_selected_functions.csv")

"""---
# Q3(c): BioGRID Analysis with CADM1 Interactors
---

## Step 6: Load BioGRID CADM1 Interaction Data

**Action Required:**

1. Go to https://thebiogrid.org/
2. Search for: **CADM1** (Homo sapiens)
3. Download the interaction data as TSV
4. Upload the file and load it below
"""

# Load the BioGRID interaction file
# Replace with your actual BioGRID file name
biogrid_df = pd.read_csv('BIOGRID-GENE-117218-5.0.251.tab3.txt', sep='\t')

print("=" * 80)
print("Q3(c): BioGRID CADM1 Interactions Analysis")
print("=" * 80)
print()

# Display basic info
print(f"Total interactions: {len(biogrid_df)}")
print()

# Show first few interactions
print("First 5 interactions:")
print(biogrid_df[['Official Symbol Interactor A', 'Official Symbol Interactor B',
                  'Experimental System']].head())
print()

"""## Step 7: Extract Unique Interacting Genes"""

# Extract unique interacting genes
# CADM1 could be in either column A or B
gene_a = biogrid_df['Official Symbol Interactor A'].unique()
gene_b = biogrid_df['Official Symbol Interactor B'].unique()

# Combine and remove CADM1 itself
all_genes = set(gene_a) | set(gene_b)
all_genes.discard('CADM1')  # Remove CADM1 itself

# Convert to sorted list
cadm1_interactors = sorted(list(all_genes))

print("=" * 80)
print("CADM1 Interacting Genes from BioGRID")
print("=" * 80)
print()
print(f"Number of unique genes interacting with CADM1: {len(cadm1_interactors)}")
print()

print("CADM1 Interacting Genes:")
print("-" * 80)
for i, gene in enumerate(cadm1_interactors, 1):
    print(f"{i:3d}. {gene}")
    if i % 5 == 0:  # Add blank line every 5 genes for readability
        print()

print()
print("=" * 80)

# Save the gene list
with open('cadm1_interactors_biogrid.txt', 'w') as f:
    f.write('\n'.join(cadm1_interactors))

print("\n✓ Gene list saved to: cadm1_interactors_biogrid.txt")

"""## Step 8: Check Overlap with Previous Gene Sets"""

print("=" * 80)
print("Checking Overlap Between Gene Sets")
print("=" * 80)
print()

# Convert to sets for overlap analysis
cadm1_interactors_set = set(cadm1_interactors)
top_15_set = set(top_15_genes)
biomarkers_set = set(biomarkers)

# Check overlaps
overlap_top15 = cadm1_interactors_set & top_15_set
overlap_biomarkers = cadm1_interactors_set & biomarkers_set

print(f"Total CADM1 interactors: {len(cadm1_interactors_set)}")
print(f"Top 15 RV genes: {len(top_15_set)}")
print(f"Biomarkers: {len(biomarkers_set)}")
print()

print("OVERLAPPING GENES:")
print("-" * 80)

if overlap_top15:
    print(f"\n✓ Overlap with Top-15 RV genes ({len(overlap_top15)}):")
    for gene in sorted(overlap_top15):
        print(f"  - {gene}")
else:
    print("\n✗ No overlap with Top-15 RV genes")

if overlap_biomarkers:
    print(f"\n✓ Overlap with Biomarkers ({len(overlap_biomarkers)}):")
    for gene in sorted(overlap_biomarkers):
        print(f"  - {gene}")
else:
    print("\n✗ No overlap with Biomarkers")

print()
print("=" * 80)

"""## Step 9: Prepare Gene List for STRING (CADM1 Network)"""

# Prepare CADM1 + interactors for STRING
all_cadm1_for_string = ['CADM1'] + cadm1_interactors

print("=" * 80)
print("Preparing CADM1 Network for STRING Analysis")
print("=" * 80)
print()

print(f"Total genes for STRING: {len(all_cadm1_for_string)}")
print(f"  - CADM1 itself: 1")
print(f"  - CADM1 interactors: {len(cadm1_interactors)}")
print()

# Create the input string for STRING
string_input_cadm1 = '\n'.join(all_cadm1_for_string)

print("STRING INPUT (copy this):")
print("=" * 80)
print(string_input_cadm1)
print("=" * 80)
print()

# Save to file
with open('string_input_cadm1_interactors.txt', 'w') as f:
    f.write(string_input_cadm1)

print("✓ Saved to: string_input_cadm1_interactors.txt")
print()

print("=" * 80)
print("NEXT ACTIONS:")
print("=" * 80)
print("1. Copy the gene list above (or from the .txt file)")
print("2. Go to STRING: https://string-db.org/")
print("3. Paste the genes")
print("4. Select organism: Homo sapiens")
print("5. Click SEARCH")
print("6. Take a screenshot of the network")
print("7. Save as: string_network_cadm1_interactors.png")
print("8. Go to 'Analysis' tab and download enrichment data")
print("9. Upload the enrichment TSV file and continue below")
print("=" * 80)

"""## Step 10: Analyze CADM1 Network Enrichment"""

# Load the enrichment file for CADM1 interactors
# Replace with your actual filename
enrichment_cadm1 = pd.read_csv('enrichment_all_q3.tsv', sep='\t')

print("=" * 80)
print("Q3(c): STRING Enrichment Analysis - CADM1 Interactors")
print("=" * 80)
print()

# Display basic info
print(f"Total enrichment terms: {len(enrichment_cadm1)}")
print()

# Count by category
print("Enrichment Categories:")
print(enrichment_cadm1['#category'].value_counts())
print()

# Show available categories
print("Available Categories:")
for cat in enrichment_cadm1['#category'].unique():
    count = len(enrichment_cadm1[enrichment_cadm1['#category'] == cat])
    print(f"  - {cat}: {count} terms")
print()

"""## Step 11: Identify Cancer-Related Functions for CADM1 Network"""

print("=" * 80)
print("CANCER-RELATED ENRICHMENT TERMS (CADM1 Interactors)")
print("=" * 80)
print()

# Look for cancer-related terms
for category in enrichment_cadm1['#category'].unique():
    cat_df = enrichment_cadm1[enrichment_cadm1['#category'] == category]

    # Filter for cancer-related terms
    cancer_terms = cat_df[
        cat_df['term description'].str.lower().str.contains('|'.join(cancer_keywords), na=False)
    ].head(10)

    if len(cancer_terms) > 0:
        print(f"\n{category.upper()}:")
        print("-" * 80)
        for idx, row in cancer_terms.iterrows():
            print(f"  {row['term ID']}: {row['term description']}")
            print(f"    Genes: {row['observed gene count']}, FDR: {row['false discovery rate']:.4f}")
            print(f"    Proteins: {row['matching proteins in your network (labels)']}")
            print()

"""## Step 12: Select Three Cancer-Related Functions (CADM1 Network)"""

print("=" * 80)
print("Q3(c): THREE SELECTED CANCER-RELATED FUNCTIONS")
print("(CADM1 Interactors)")
print("=" * 80)
print()

print("FUNCTION 1: Endometrial Cancer Pathway")
print("  Category: KEGG Pathway")
print("  Term ID: hsa05213")
print("  Genes: KRAS, ERBB2, EGFR, GSK3B, HRAS")
print("  FDR: 0.0001")
print()

print("FUNCTION 2: ErbB Signaling Pathway")
print("  Category: KEGG Pathway")
print("  Term ID: hsa04012")
print("  Genes: KRAS, ERBB2, EGFR, GSK3B, HRAS")
print("  FDR: 0.0003")
print()

print("FUNCTION 3: Virus Receptor Activity")
print("  Category: GO Molecular Function")
print("  Term ID: GO:0001618")
print("  Genes: EGFR, BSG, HSPA1A, ACE2, PVR, LDLR")
print("  FDR: 0.0002")
print()

print("=" * 80)

# Save the selected functions
selected_functions_q3c = pd.DataFrame({
    'Function': [
        'Endometrial Cancer Pathway',
        'ErbB Signaling Pathway',
        'Virus Receptor Activity'
    ],
    'Category': ['KEGG Pathway', 'KEGG Pathway', 'GO Molecular Function'],
    'Term ID': ['hsa05213', 'hsa04012', 'GO:0001618'],
    'Genes': [
        'KRAS, ERBB2, EGFR, GSK3B, HRAS',
        'KRAS, ERBB2, EGFR, GSK3B, HRAS',
        'EGFR, BSG, HSPA1A, ACE2, PVR, LDLR'
    ],
    'FDR': [0.0001, 0.0003, 0.0002]
})

selected_functions_q3c.to_csv('q3c_selected_functions.csv', index=False)
print("\n✓ Selected functions saved to: q3c_selected_functions.csv")

"""---
# Summary and Comparison
---

## Step 13: Compare Results from Q3(a/b) vs Q3(c)
"""

print("=" * 80)
print("COMPARATIVE ANALYSIS: Q3(a+b) vs Q3(c)")
print("=" * 80)
print()

print("Q3(a/b): Top-15 RV Genes + Biomarkers")
print("-" * 80)
print("Focus: Metabolic reprogramming and hypoxia response")
print("Key genes: HIF1A, PKM, SLC2A1")
print("Main pathways:")
print("  1. Central carbon metabolism in cancer")
print("  2. Glucose metabolism in TNBC")
print("  3. HIF1A regulation of glycolysis")
print()

print("Q3(c): CADM1 Interactors")
print("-" * 80)
print("Focus: Growth factor signaling and receptor activity")
print("Key genes: EGFR, ERBB2, KRAS, HRAS, GSK3B")
print("Main pathways:")
print("  1. Endometrial cancer pathway")
print("  2. ErbB signaling pathway")
print("  3. Virus receptor activity")
print()

print("KEY OBSERVATIONS:")
print("-" * 80)
print("• No overlap between CADM1 interactors and top-15 RV genes/biomarkers")
print("• Q3(a/b) focuses on metabolism; Q3(c) focuses on signaling")
print("• Both analyses converge on cancer-related processes")
print("• Complementary mechanisms of cancer progression")
print()

print("=" * 80)

"""## Step 14: Create Summary Visualizations"""

# Create a summary comparison figure
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Q3(a/b) Functions
functions_q3b = ['Central Carbon\nMetabolism', 'TNBC Glucose\nMetabolism',
                 'HIF1A Regulation\nof Glycolysis']
fdr_q3b = [0.0140, 0.0083, 0.0083]

axes[0].barh(functions_q3b, [-np.log10(f) for f in fdr_q3b],
             color='steelblue', edgecolor='black', linewidth=1.5)
axes[0].set_xlabel('-log10(FDR)', fontsize=12, fontweight='bold')
axes[0].set_title('Q3(a/b): Top-15 RV + Biomarkers\nCancer Functions',
                  fontsize=13, fontweight='bold')
axes[0].axvline(-np.log10(0.05), color='red', linestyle='--', linewidth=2,
                label='FDR = 0.05')
axes[0].legend()
axes[0].grid(True, alpha=0.3, axis='x')

# Q3(c) Functions
functions_q3c = ['Endometrial\nCancer', 'ErbB\nSignaling',
                 'Virus Receptor\nActivity']
fdr_q3c = [0.0001, 0.0003, 0.0002]

axes[1].barh(functions_q3c, [-np.log10(f) for f in fdr_q3c],
             color='coral', edgecolor='black', linewidth=1.5)
axes[1].set_xlabel('-log10(FDR)', fontsize=12, fontweight='bold')
axes[1].set_title('Q3(c): CADM1 Interactors\nCancer Functions',
                  fontsize=13, fontweight='bold')
axes[1].axvline(-np.log10(0.05), color='red', linestyle='--', linewidth=2,
                label='FDR = 0.05')
axes[1].legend()
axes[1].grid(True, alpha=0.3, axis='x')

plt.tight_layout()
plt.savefig('q3_functions_comparison.png', dpi=300, bbox_inches='tight')
print("✓ Saved: q3_functions_comparison.png")
plt.show()

"""---
# Final Summary
---
"""

print("=" * 80)
print("Q3 COMPLETE SUMMARY")
print("=" * 80)
print()

print("Q3(a): STRING Network Analysis ✓")
print("-" * 80)
print(f"  • Input: {len(all_genes_for_string)} genes (top-15 RV + 7 biomarkers)")
print("  • Network: Successfully generated")
print("  • File: string_network_top15_biomarkers.png")
print()

print("Q3(b): Three Cancer-Related Functions ✓")
print("-" * 80)
print("  1. Central Carbon Metabolism in Cancer (KEGG)")
print("  2. Glucose Metabolism in TNBC (WikiPathways)")
print("  3. HIF1A and PPARG Regulation (WikiPathways)")
print("  • All FDR < 0.015")
print("  • Focus: Metabolic reprogramming")
print()

print("Q3(c): BioGRID CADM1 Analysis ✓")
print("-" * 80)
print(f"  • CADM1 interactors identified: {len(cadm1_interactors)}")
print(f"  • STRING analysis: {len(all_cadm1_for_string)} genes")
print("  • Network: string_network_cadm1_interactors.png")
print()
print("  Three Cancer-Related Functions:")
print("  1. Endometrial Cancer Pathway (KEGG)")
print("  2. ErbB Signaling Pathway (KEGG)")
print("  3. Virus Receptor Activity (GO)")
print("  • All FDR < 0.0003")
print("  • Focus: Growth factor signaling")
print()

print("FILES GENERATED:")
print("-" * 80)
print("Gene Lists:")
print("  • string_input_genes.txt")
print("  • cadm1_interactors_biogrid.txt")
print("  • string_input_cadm1_interactors.txt")
print()
print("Results:")
print("  • q3b_selected_functions.csv")
print("  • q3c_selected_functions.csv")
print("  • q3_functions_comparison.png")
print()
print("Network Images (screenshots from STRING):")
print("  • string_network_top15_biomarkers.png")
print("  • string_network_cadm1_interactors.png")
print()

print("=" * 80)
print("✅ Q3 COMPLETED SUCCESSFULLY!")
print("=" * 80)
print()

print("KEY FINDINGS:")
print("  • Identified distinct cancer mechanisms through two approaches")
print("  • Metabolism-focused pathways (Q3a/b) vs Signaling-focused pathways (Q3c)")
print("  • All identified functions are statistically significant (FDR < 0.015)")
print("  • Both gene sets show strong cancer relevance")
print("  • CADM1 interacts with core oncogenic signaling molecules")
print()
print("=" * 80)